---
apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: githubrepo
  labels:
    kratix.io/promise-version: v0.0.2
  namespace: default
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: githubrepos.promise.platform.giantswarm.io
    spec:
      group: promise.platform.giantswarm.io
      scope: Namespaced
      names:
        plural: githubrepos
        singular: githubrepo
        kind: githubrepo
      versions:
        - name: v1beta1
          served: true
          storage: true
          schema:
            openAPIV3Schema:
              type: object
              properties:
                spec:
                  type: object
                  required:
                    - backstageCatalogEntity
                    - repository
                    - registryInfoConfigMapRef
                  properties:
                    backstageCatalogEntity:
                      description: Backstage catalog entity configuration
                      required:
                        - owner
                        - lifecycle
                      type: object
                      properties:
                        owner:
                          description: A reference of the owning Backstage entity.
                          type: string
                        lifecycle:
                          description: A lifecycle of the Backstage entity.
                          type: string
                    repository:
                      description: New repository configuration.
                      required:
                        - owner
                        - name
                        - description
                        - templateSource
                        - visibility
                      type: object
                      properties:
                        owner:
                          description: A name of the owning GitHub organization or user.
                          type: string
                        name:
                          description: A name for the new repository.
                          type: string
                        description:
                          description: A description of the new repository.
                          type: string
                        templateSource:
                          description: A full name (`user/repository`) of a GitHub template repository to use.
                          type: string
                        visibility:
                          description: Visibility of the created repo.
                          enum:
                            - public
                            - internal
                            - private
                          type: string
                    githubTokenSecretRef:
                      description: >-
                        The name and namespace of a Secret that has a key named "gh_token" with value if a GitHub
                        authentication token used to create a new repository.
                      required:
                        - name
                      type: object
                      properties:
                        name:
                          description: Object name.
                          type: string
                        namespace:
                          description: Object's namespace.
                          type: string
                    registryInfoConfigMapRef:
                      description: >-
                        The name and namespace of a ConfigMap that has keys named "registry_domain", 
                        "registry_username" and "registry_cicd_secret_ref" that configure access to 
                        the image registry in the CICD GitHib Action.
                      required:
                        - name
                      type: object
                      properties:
                        name:
                          description: Object name.
                          type: string
                        namespace:
                          description: Object's namespace.
                          type: string
  workflows:
    resource:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: github-repo-create
          spec:
            rbac:
              permissions:
                - apiGroups: [""]
                  verbs: ["get", "list"]
                  resources: ["secrets"]
                - apiGroups: [""]
                  verbs: ["get", "list"]
                  resources: ["configmaps"]
            volumes:
              - name: repo
                emptyDir: {}
            containers:
              - name: github-cli-clone-template-repo-pipeline
                image: gsoci.azurecr.io/giantswarm/github-cli-clone-template-repo-pipeline
                imagePullPolicy: Always
              - name: github-cli-template-values-pipeline
                image: gsoci.azurecr.io/giantswarm/github-cli-template-values-pipeline
                imagePullPolicy: Always
                volumeMount:
                  - name: repo
                    mountPath: /tmp/repo
