apiVersion: promise.platform.giantswarm.io/v1beta1
kind: githubrepo
metadata:
  name: my-go-project-1
spec:
  backstageCatalogEntity:
    owner: group:default/team-platform
    lifecycle: experimental
    grafanaDashboard: cdyhcdr5hge0wa/demotech-web-application-vitals
  repository:
    name: my-go-project-1
    owner: DemoTechInc
    description: "My first kratix project"
    templateSource: giantswarm/devplatform-template-go-service
    visibility: private
  registryInfoConfigMapRef:
    name: github-oci-registry-info
  githubTokenSecretRef:
    name: dev-platform-gh-access
