version: 2.1
orbs:
  architect: giantswarm/architect@5.10.1

jobs:
  execute-tests:
    machine:
      image: default
    parameters:
      promise-dir:
        type: string
    steps:
      - checkout
      - run: "cd /usr/bin && curl -fsSL https://github.com/yannh/kubeconform/releases/download/v0.6.7/kubeconform-linux-amd64.tar.gz | sudo tar xzf - && cd -"
      - run: "pyenv global 3 && python -m venv env && source env/bin/activate"
      - run: "python --version && pip install pyyaml"
      - run: "cd ./<< parameters.promise-dir >> && FAIL_FAST=true ./test-all.sh"

workflows:
  build-app-deployment-promise:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: build-appdeployment-template
          image: giantswarm/appdeployment-template-pipeline
          dockerfile: ./app-deployment-promise/containers/appdeployment-template-pipeline/Dockerfile
          build-context: ./app-deployment-promise/containers
          git-tag-prefix: app-deployment-promise
          registries-data: |-
            public gsoci.azurecr.io ACR_GSOCI_USERNAME ACR_GSOCI_PASSWORD true
          # filters:
          # tags:
          # only: /.*/
      - architect/push-to-registries:
          context: architect
          name: build-provision-infrastructure
          image: giantswarm/provision-infrastructure-pipeline
          dockerfile: ./app-deployment-promise/containers/provision-infrastructure-pipeline/Dockerfile
          build-context: ./app-deployment-promise/containers
          git-tag-prefix: app-deployment-promise
          registries-data: |-
            public gsoci.azurecr.io ACR_GSOCI_USERNAME ACR_GSOCI_PASSWORD true
          # filters:
          # tags:
          # only: /.*/
      - execute-tests:
          promise-dir: "app-deployment-promise"
          requires:
            - build-appdeployment-template
            - build-provision-infrastructure
          filters:
            tags:
              only: /app-deployment-promise\/.*/
