version: 2.1
setup: true

orbs:
  dynamic: bjd2385/dynamic-continuation@3.9.0

workflows:
  build:
    jobs:
      - dynamic/continue:
          name: "Dynamic continuation - Force all modules on tags"
          context: circleci
          auto-detect: true
          # Disable root config detection by setting this to nonsense, otherwise 'app' is replaced
          # in the detect module names as '.'.
          # See: https://github.com/emmeowzing/dynamic-continuation-orb/blob/v3.9.0/src/jobs/continue.yml#L84-L87
          root-config: the-owls-are-not-what-they-seem
          force-all: true
          filters:
            tags:
              only: "/^.*/"
            branches:
              ignore: "/^.*/"
      - dynamic/continue:
          name: "Dynamic continuation - Branches"
          context: circleci
          auto-detect: true
          # Disable root config detection by setting this to nonsense, otherwise 'app' is replaced
          # in the detect module names as '.'.
          # See: https://github.com/emmeowzing/dynamic-continuation-orb/blob/v3.9.0/src/jobs/continue.yml#L84-L87
          root-config: the-owls-are-not-what-they-seem
          force-all: false
          filters:
            branches:
              ignore: "main"
