version: "2.1"
setup: true

orbs:
  dynamic: bjd2385/dynamic-continuation@3.9.0

jobs: {}

workflows:
  on-commit:
    jobs:
      - dynamic/continue:
          context: circleci
          auto-detect: true
