version: 2.1
orbs:
  architect: giantswarm/architect@5.2.1

workflows:
  build-app-deployment-promise-appdeployment-template:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: build-appdeployment-template
          image: giantswarm/appdeployment-template-pipeline
          dockerfile: ./app-deployment-promise/containers/appdeployment-template-pipeline/Dockerfile
          build-context: ./app-deployment-promise/containers
          registries-data: |-
            public gsoci.azurecr.io ACR_GSOCI_USERNAME ACR_GSOCI_PASSWORD true
      - architect/push-to-registries:
          context: architect
          name: build-check-if-infra-ready
          image: giantswarm/check-if-infra-ready-pipeline
          dockerfile: ./app-deployment-promise/containers/check-if-infra-ready-pipeline/Dockerfile
          build-context: ./app-deployment-promise/containers
          registries-data: |-
            public gsoci.azurecr.io ACR_GSOCI_USERNAME ACR_GSOCI_PASSWORD true
      - architect/push-to-registries:
          context: architect
          name: build-provision-infrastructure
          image: giantswarm/provision-infrastructure-pipeline
          dockerfile: ./app-deployment-promise/containers/provision-infrastructure-pipeline/Dockerfile
          build-context: ./app-deployment-promise/containers
          registries-data: |-
            public gsoci.azurecr.io ACR_GSOCI_USERNAME ACR_GSOCI_PASSWORD true
