version: 2.1
orbs:
  architect: giantswarm/architect@6.6.0

jobs:
  execute-tests-github-app-promise:
    machine:
      image: default
    parameters:
      promise-dir:
        type: string
    steps:
      - checkout
      - run: "cd /usr/bin && curl -fsSL https://github.com/yannh/kubeconform/releases/download/v0.6.7/kubeconform-linux-amd64.tar.gz | sudo tar xzf - && cd -"
      - run: "pyenv global 3 && python -m venv env && source env/bin/activate"
      - run: "python --version && pip install pyyaml"
      - run: "cd ./<< parameters.promise-dir >> && FAIL_FAST=true ./test-all.sh"

workflows:
  build-github-app-promise:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: build-githubapp-template-repo
          image: giantswarm/githubapp-template-pipeline
          dockerfile: ./github-app-promise/containers/githubapp-template-pipeline/Dockerfile
          git-tag-prefix: githubapp-template-pipeline
          build-context: ./github-app-promise/containers
          registries-data: |-
            public gsoci.azurecr.io ACR_GSOCI_USERNAME ACR_GSOCI_PASSWORD true
          filters:
            tags:
              only: "/^githubapp-template-pipeline.*/"
            branches:
              ignore: "main"
      - execute-tests-github-app-promise:
          promise-dir: "github-app-promise"
          requires:
            - build-githubapp-template-repo
          filters:
            tags:
              only: "/^github-app-promise.*/"
            branches:
              ignore: "main"
