version: 2.1
orbs:
  architect: giantswarm/architect@5.10.1

workflows:
  build-kratix-kubectl-cli:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: build-kratix-kubectl-cli
          image: giantswarm/kratix-kubectl-cli
          dockerfile: ./kratix-kubectl-cli/Dockerfile
          git-tag-prefix: kratix-kubectl-cli
          build-context: ./kratix-kubectl-cli/
          registries-data: |-
            public gsoci.azurecr.io ACR_GSOCI_USERNAME ACR_GSOCI_PASSWORD true
          filters:
            tags:
              only: "/^kratix-kubectl-cli.*/"
            branches:
              ignore: "main"
