apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  # TODO: check why it didn't work and enable back
  # annotations:
  # kustomize.toolkit.fluxcd.io/ssa: ${my-go-project-1-ssa:=Ignore}
  name: my-go-project-1
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: test-hg-repo
      version: ">0.1.0"
      sourceRef:
        kind: HelmRepository
        name: test-helm-repo
        # Disable until Flux v2.2.0 cos keyless verification is not supported before that
        # or support key based signing: https://gigantic.slack.com/archives/C02GDJJ68Q1/p1723710023444289?thread_ts=1722593976.383529&cid=C02GDJJ68Q1
  #      verify:
  #        provider: cosign
  suspend: false
  timeout: "3m"
  values:
    autoscaling:
      enabled: false
    database:
      connectionSecretName: fill-me
      name: fill-me
    inMemoryStore: false
    ingress:
      annotations:
        kubernetes.io/tls-acme: "true"
      enabled: true
      host: fill-me
      tls:
        - hosts:
            - fill-me
          secretName: fill-me
    monitoring:
      serviceMonitor:
        enabled: true
        extraLabels:
          application.giantswarm.io/team: fill-me
    pdb:
      enabled: false
    redisConnectionSecretName: demotech-rcc-elasticache-user
