apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: ${my-go-project-1-ssa:=Ignore}
  name: my-go-project-1
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: test-hg-repo
      version: ">0.1.0"
      sourceRef:
        kind: HelmRepository
        name: test-helm-repo
        # Disable until Flux v2.2.0 cos keyless verification is not supported before that
        # or support key based signing: https://gigantic.slack.com/archives/C02GDJJ68Q1/p1723710023444289?thread_ts=1722593976.383529&cid=C02GDJJ68Q1
#      verify:
#        provider: cosign
  # This should not be set when kubeconfig is set as well!
#  serviceAccountName: automation
  suspend: false
  timeout: "3m"
