apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-go-project-1
spec:
  interval: 1m
  chart:
    spec:
      chart: test-hg-repo
      version: ">0.1.0"
      sourceRef:
        kind: HelmRepository
        name: test-helm-repo
      verify:
        provider: cosign
  suspend: false
  timeout: "3m"
