apiVersion: promise.platform.giantswarm.io/v1beta1
kind: appdeployment
metadata:
  name: laszlo-kratix-2
  namespace: org-kratix-demo
spec:
  interval: 1m
  statusConfigMapReference:
    name: laszlo-kratix-2-info
  database:
    engine: aurora-postgresql
    providerConfigRef:
      name: go-service-1-postgresql-provider-config
    eso:
      clusterSsaField: go_service_1
      tenantCluster:
        apiServerEndpoint: rdsapp-apiserver-1047606037.eu-west-2.elb.amazonaws.com
        clusterName: rdsapp
        enabled: true
  version: ">=0.1.0"
#  dependsOn:
#    - test1
#  kubeConfig:
#    secretRef:
#      name: stage-kubeconfig
  suspend: false
  timeout: 3m
#  values:
#    enableDb: true
#  valuesFrom:
#    - kind: Secret
#      name: prod-tls-values
#      valuesKey: crt
#      targetPath: tls.crt
#      optional: true
  values:
    ingress:
      enabled: false
    autoscaling:
      enabled: false
    pdb:
      enabled: false
    monitoring:
      serviceMonitor:
        enabled: false
