apiVersion: promise.platform.giantswarm.io/v1beta1
kind: appdeployment
metadata:
  name: my-go-project-1
  namespace: default
spec:
  interval: 1m
  version: ">=0.1.0"
  dependsOn:
    - name: test1
  database:
    engine: aurora-postgresql
    providerConfigRef:
      name: my-go-project-1-postgresql-provider-config
    eso:
      clusterSsaField: my_go_project_1
      tenantCluster:
        apiServerEndpoint: rdsapp-apiserver-1047606037.eu-west-2.elb.amazonaws.com
        clusterName: rdsapp
        enabled: true
  kubeConfig:
    secretRef:
      name: stage-kubeconfig
  suspend: false
  timeout: 3m
  values:
    enableDb: true
  valuesFrom:
    - kind: Secret
      name: prod-tls-values
      valuesKey: crt
      targetPath: tls.crt
      optional: true
  statusConfigMapReference:
    name: my-go-project-1-info
