---
apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: appdeployment
  labels:
    kratix.io/promise-version: v0.0.1
  namespace: default
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: appdeployments.promise.platform.giantswarm.io
    spec:
      group: promise.platform.giantswarm.io
      scope: Namespaced
      names:
        plural: appdeployments
        singular: appdeployment
        kind: appdeployment
      versions:
        - name: v1beta1
          served: true
          storage: true
          schema:
            openAPIV3Schema:
              description: AppDeployment
              type: object
              required:
                - spec
              properties:
                spec:
                  type: object
                  required:
                    - database
                    - interval
                    - statusConfigMapReference
                  description: AppDeploymentSpec defines the desired state of a Helm release and Logical Database.
                  properties:
                    database:
                      description: Logical database related information.
                      type: object
                      required:
                        - engine
                        - eso
                        - providerConfigRef
                      properties:
                        engine:
                          description: Database engine of the referenced database cluster.
                          type: string
                        eso:
                          description: ESO related configuration.
                          type: object
                          required:
                            - ssaField
                          properties:
                            ssaField:
                              description: Field name that indicates the database cluster being ready in the Flux SSA secret.
                              type: string
                            tenantCluster:
                              description: Tenant cluster related configuration.
                              type: object
                              properties:
                                apiServerEndpoint:
                                  description: URL of the tenant cluster API servers.
                                  type: string
                                clusterName:
                                  description: Name of the tenant workload cluster.
                                  type: string
                                enabled:
                                  description: Switch for the tenant cluster configuration.
                                  type: boolean
                                  default: false
                        providerConfigRef:
                          description: Database provider config reference information.
                          type: object
                          required:
                            - name
                          properties:
                            name:
                              description: Name of the provider config reference object for the given database engine.
                              type: string
                    dependsOn:
                      description: |-
                        DependsOn may contain a meta.NamespacedObjectReference slice with
                        references to AppDeployment resources that must be ready before this AppDeployment
                        can be reconciled.
                      items:
                        description: |-
                          NamespacedObjectReference contains enough information to locate the referenced Kubernetes resource object in any
                          namespace.
                        properties:
                          name:
                            description: Name of the referent.
                            type: string
                          namespace:
                            description:
                              Namespace of the referent, when not specified it
                              acts as LocalObjectReference.
                            type: string
                        required:
                          - name
                        type: object
                      type: array
                    interval:
                      description: Interval at which to reconcile the Helm release.
                      pattern: ^([0-9]+(\.[0-9]+)?(ms|s|m|h))+$
                      default: "1m"
                      type: string
                    kubeConfig:
                      description: |-
                        KubeConfig for reconciling the HelmRelease on a remote cluster.
                        When used in combination with HelmReleaseSpec.ServiceAccountName,
                        forces the controller to act on behalf of that Service Account at the
                        target cluster.
                        If the --default-service-account flag is set, its value will be used as
                        a controller level fallback for when HelmReleaseSpec.ServiceAccountName
                        is empty.
                      properties:
                        secretRef:
                          description: |-
                            SecretRef holds the name of a secret that contains a key with
                            the kubeconfig file as the value. If no key is set, the key will default
                            to 'value'.
                            It is recommended that the kubeconfig is self-contained, and the secret
                            is regularly updated if credentials such as a cloud-access-token expire.
                            Cloud specific `cmd-path` auth helpers will not function without adding
                            binaries and credentials to the Pod that is responsible for reconciling
                            Kubernetes resources.
                          properties:
                            key:
                              description:
                                Key in the Secret, when not specified an implementation-specific
                                default key is used.
                              type: string
                            name:
                              description: Name of the Secret.
                              type: string
                          required:
                            - name
                          type: object
                      required:
                        - secretRef
                      type: object
                    statusConfigMapReference:
                      type: object
                      required:
                        - name
                      description: |-
                        Reference to an already existing 'status' ConfigMap generated by a "*repo" Promise in the same namespace.
                      properties:
                        name:
                          maxLength: 2048
                          minLength: 1
                          type: string
                    suspend:
                      description: |-
                        Suspend tells the controller to suspend reconciliation for this AppDeployment,
                        it does not apply to already started reconciliations. Defaults to false.
                      type: boolean
                      default: false
                    timeout:
                      description: Timeout when reconciling the Helm release.
                      pattern: ^([0-9]+(\.[0-9]+)?(ms|s|m|h))+$
                      default: "3m"
                      type: string
                    values:
                      description: Values holds the values for this Helm release.
                      x-kubernetes-preserve-unknown-fields: true
                    valuesFrom:
                      description: |-
                        ValuesFrom holds references to resources containing Helm values for this AppDeployment,
                        and information about how they should be merged.
                      items:
                        description: |-
                          ValuesReference contains a reference to a resource containing Helm values,
                          and optionally the key they can be found at.
                        properties:
                          kind:
                            description:
                              Kind of the values referent, valid values are ('Secret',
                              'ConfigMap').
                            enum:
                              - Secret
                              - ConfigMap
                            type: string
                          name:
                            description: |-
                              Name of the values referent. Should reside in the same namespace as the
                              referring resource.
                            maxLength: 253
                            minLength: 1
                            type: string
                          optional:
                            description: |-
                              Optional marks this ValuesReference as optional. When set, a not found error
                              for the values reference is ignored, but any ValuesKey, TargetPath or
                              transient error will still result in a reconciliation failure.
                            type: boolean
                          targetPath:
                            description: |-
                              TargetPath is the YAML dot notation path the value should be merged at. When
                              set, the ValuesKey is expected to be a single flat value. Defaults to 'None',
                              which results in the values getting merged at the root.
                            maxLength: 250
                            pattern: ^([a-zA-Z0-9_\-.\\\/]|\[[0-9]{1,5}\])+$
                            type: string
                          valuesKey:
                            description: |-
                              ValuesKey is the data key where the values.yaml or a specific value can be
                              found at. Defaults to 'values.yaml'.
                            maxLength: 253
                            pattern: ^[\-._a-zA-Z0-9]+$
                            type: string
                        required:
                          - kind
                          - name
                        type: object
                      type: array
                    version:
                      default: "*"
                      description: |-
                        Version semver expression, ignored for charts from v1.GitRepository and
                        v1beta2.Bucket sources. Defaults to latest when omitted.
                      type: string
  workflows:
    resource:
      configure:
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: provision-infra
          spec:
            containers:
              - name: crossplane-provisioner
                image: gsoci.azurecr.io/giantswarm/provision-infrastructure-pipeline
                imagePullPolicy: Always
        - apiVersion: platform.kratix.io/v1alpha1
          kind: Pipeline
          metadata:
            name: template
          spec:
            containers:
              #              - name: wait-for-infra
              #                image: gsoci.azurecr.io/giantswarm/check-if-infra-ready-pipeline
              #                imagePullPolicy: Always
              - name: template-values
                image: gsoci.azurecr.io/giantswarm/appdeployment-template-pipeline
                imagePullPolicy: Always
            rbac:
              permissions:
                - apiGroups: [""]
                  verbs: ["get", "list"]
                  resources: ["configmaps"]
