apiVersion: promise.platform.giantswarm.io/v1beta1
kind: GitHubApp
metadata:
  name: my-go-project-1
spec:
  githubapp:
    name: my-go-project-1
    spec:
      repository:
        name: my-go-project-1
        owner: DemoTechInc
        description: "My first kratix project"
        templateSource: giantswarm/devplatform-template-go-service
        visibility: private
      registryInfoConfigMapRef:
        name: github-oci-registry-info
      githubTokenSecretRef:
        name: dev-platform-gh-access
  appdeployment:
    name: my-go-project-dev
    spec:
      interval: 1m
      version: ">=0.1.0"
      kubeConfig:
        secretRef:
          name: stage-kubeconfig
      suspend: false
      timeout: 3m
      values:
        enableDb: true
      valuesFrom:
        - kind: Secret
          name: prod-tls-values
          valuesKey: crt
          targetPath: tls.crt
          optional: true
