apiVersion: xdatabase.crossplane.giantswarm.io/v1alpha1
kind: LogicalDatabaseClaim
metadata:
  name: fill-me
  namespace: default
spec:
  deletionPolicy: Delete
  engine: aurora-postgresql
  eso:
    enabled: true
    fluxSSASecretName: fluxssa
    kubernetesSecretStore: default
    tenantCluster:
      apiServerEndpoint: demotech-rds-apiserver-852993111.eu-central-1.elb.amazonaws.com
      clusterName: demotech-rds
      enabled: true
  kubernetesProviderConfig:
    name: default
  managementPolicies:
    - "*"
  providerConfigRef:
    name: demotech-rcc-postgresql-provider-config
